#!/usr/bin/env bash

set -Eeuo pipefail

# Typecheck & lint the whole codebase before push - saves us from having to catch lint errors in CI
pnpm lint

if [[ -z "${NO_BUILD:-}" ]]; then
  pnpm build
else
  echo "Skipping pnpm build (NO_BUILD set)"
fi
